Track.create([{ track_name: "Track 1 - Pattern Recognition" },
              { track_name: "Track 2 - Image, Speech, and Signal Processing" },
              { track_name: "Track 3 - Document Analysis" },
              { track_name: "Track 4 - Biometrics" },
              { track_name: "Track 5 - Bioinformatics"
                }])

SessionTrack.create([{ session_id: 1, track_id: 1 },
                     { session_id: 1, track_id: 2 },
                     { session_id: 1, track_id: 3 },
                     { session_id: 1, track_id: 4 },
                     { session_id: 1, track_id: 5 },
                     { session_id: 2, track_id: 1 },
                     { session_id: 2, track_id: 2 },
                     { session_id: 2, track_id: 3 },
                     { session_id: 2, track_id: 4 },
                     { session_id: 2, track_id: 5 },
                     { session_id: 3, track_id: 4 },
                     { session_id: 4, track_id: 1 },
                     { session_id: 5, track_id: 2 },
                     { session_id: 6, track_id: 3 },
                     { session_id: 7, track_id: 2 },
                     { session_id: 8, track_id: 1 },
                     { session_id: 8, track_id: 2 },
                     { session_id: 8, track_id: 3 },
                     { session_id: 8, track_id: 4 },
                     { session_id: 8, track_id: 5 },
                     { session_id: 9, track_id: 1 },
                     { session_id: 10, track_id: 3 },
                     { session_id: 11, track_id: 5 },
                     { session_id: 12, track_id: 2 },
                     { session_id: 13, track_id: 5 },
                     { session_id: 14, track_id: 1 },
                     { session_id: 14, track_id: 2 },
                     { session_id: 14, track_id: 3 },
                     { session_id: 14, track_id: 4 },
                     { session_id: 14, track_id: 5 },
                     { session_id: 15, track_id: 1 },
                     { session_id: 15, track_id: 2 },
                     { session_id: 15, track_id: 3 },
                     { session_id: 15, track_id: 4 },
                     { session_id: 15, track_id: 5 },
                     { session_id: 16, track_id: 1 },
                     { session_id: 16, track_id: 2 },
                     { session_id: 16, track_id: 3 },
                     { session_id: 16, track_id: 4 },
                     { session_id: 16, track_id: 5 },
                     { session_id: 17, track_id: 2 },
                     { session_id: 18, track_id: 1 },
                     { session_id: 19, track_id: 2 },
                     { session_id: 20, track_id: 1 },
                     { session_id: 21, track_id: 1 },
                     { session_id: 21, track_id: 2 },
                     { session_id: 21, track_id: 3 },
                     { session_id: 21, track_id: 4 },
                     { session_id: 21, track_id: 5 },
                     { session_id: 22, track_id: 1 },
                     { session_id: 23, track_id: 1 },
                     { session_id: 24, track_id: 2 },
                       ])
